# .github/workflows/testandopenpr.yml
name: Test and Open PR
on: 
    push:
        branches:
            - dev/*
permissions:
  contents: write
  pull-requests: write

  
jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: 3.11

            - name: Install dependencies
              run: |
                pip install -r requirements.txt
                pip install pytest

            - name: Run Tests
              run: pytest -v

            - name: Open Pull Request to master
              if: success()
              uses: peter-evans/create-pull-request@v6
              with:
                token: ${{secrets.GITHUB_TOKEN}}
                branch: auto-pr/${{github.run_number}}
                title: 'Automatic Pull Request After Successful tests from ${{ github.ref_name}}'
                body: |
                    All tests passed and PR from `${{github.ref_name}}` automatically created by Github Actions.
                base: master
                delete-branch: true 



